<!doctype html>
<html lang="fr">
<head>
    <meta charset="utf-8">
    <meta http-equiv="x-ua-compatible" content="ie=edge">
    <title>HOTEL Continental St Julian's</title>
    <meta name="description" content="Description de l'application">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" href="app/www/css/fonts.css">
    <link rel="stylesheet" href="app/www/css/normalize.css">
    <link rel="stylesheet" href="app/www/css/main.css">
    <link rel="stylesheet" href="app/www/css/style.css">
</head>
<body>
    <h1>Hotel Continental St Julian's</h1>

    <?php include $app['view'] ?>

    <script src="app/www/js/vendor/modernizr-3.7.1.min.js"></script>
    <script src="https://code.jquery.com/jquery-3.4.1.min.js" integrity="sha256-CSXorXvZcTkaix6Yvo6HppcZGetbYMGWSFlBw8HfCJo=" crossorigin="anonymous"></script>
    <script>window.jQuery || document.write('<script src="app/www/js/vendor/jquery-3.4.1.min.js"><\/script>')</script>
    <script src="app/www/js/plugins.js"></script>
    <script src="app/www/js/main.js"></script>
</body>
</html>
